# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fbb149686222c7c5c2168256ba1d73212ea0121600c72835e32f5f41275a992102c8c246724cfaa73408f52776ae3357a80a50b4e7bdc6eb3dfea9033c5576

test:
  secret_key_base: 6550b0f419c2976771110e0beb365183dc1e0bcda9966353fffb8c8fdbacf1a653832adcc02b19605da6f7bcaa163eaaab531a54e3ff598442de6990d51592f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
